# -*- coding: utf-8 -*-
"""assignment_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lw0nioP9TmqEZm4qnE-to2ZnTBvJTR_P

# Edge AI Assignment: Neural Network from Scratch (Checkerboard Classification)

## Objective
Build a simple neural network **from scratch (no ML libraries)** to classify a 2D checkerboard pattern.

You will:
- Implement forward propagation
- Implement backpropagation
- Train a small neural network
- Visualize the decision boundary

---

## Dataset Concept
We generate (x, y) points and assign labels based on a checkerboard pattern.

This is a **non-linear classification problem** (like XOR, but extended to 2D).
"""

import numpy as np
import matplotlib.pyplot as plt

"""## Step 1: Generate Checkerboard Data"""

def generate_data(n_samples=5000, k=4):
    X = np.random.uniform(-1, 1, (n_samples, 2))

    # Checkerboard labels
    y = ((np.floor((X[:,0]+1)*k) + np.floor((X[:,1]+1)*k)) % 2)

    return X, y.reshape(-1, 1)

X, y = generate_data()

"""## Visualize Dataset"""

plt.scatter(X[:,0], X[:,1], c=y.flatten())
plt.title("Checkerboard Dataset")
plt.show()

"""
## Step 2: Build Neural Network

Architecture:
- Input: 2 neurons (x, y)
- Hidden: YOU DECIDE
- Output: 1 neuron (sigmoid)

Fill in missing parts.
"""

# Initialize weights
def init_params(input_size, hidden_size, output_size):
    W1 = np.random.randn(input_size, hidden_size)
    b1 = np.zeros((1, hidden_size))

    W2 = np.random.randn(hidden_size, output_size)
    b2 = np.zeros((1, output_size))

    return W1, b1, W2, b2

"""## Activation Functions"""

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)
    pass

"""## Forward Pass"""

def forward(X, W1, b1, W2, b2):
    # TODO:
    # 1. Hidden layer linear combination
    hidden_input = np.dot(X,W1)+b1
    # 2. Activation
    hidden_output = np.sigmoid( hidden_input )
    # 3. Output layer
    final_input = np.dot(hidden_output, W2)+b2
    final_output = np.sigmoid( final_input )
    # 4. Return output + intermediates
    return hidden_input, hidden_output, final_input, final_output
    pass

"""## Loss Function"""

def compute_loss(y_true, y_pred):
    # TODO: Binary cross-entropy
    pass

"""## Backpropagation

X is the input, y error W1, b1, W2, b2 are the original weights
"""

def backward(X, y, W1, b1, W2, b2, cache):
    # TODO:
    # Compute gradients for all parameters
    pass

"""## Training Loop"""

def train(X, y, hidden_size=8, lr=0.1, epochs=1000):
    W1, b1, W2, b2 = init_params(2, hidden_size, 1)

    for epoch in range(epochs):
        # Forward
        hidden_input, hidden_output, final_input, final_output = forward( X, W1, b1, W2, b2)

        # Loss
        # TODO

        # Backward
        # TODO

        # Update weights
        # TODO

        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: ???")

    return W1, b1, W2, b2

"""## Visualize Decision Boundary"""

def plot_decision_boundary(X, y, model):
    xx, yy = np.meshgrid(np.linspace(-1,1,100), np.linspace(-1,1,100))
    grid = np.c_[xx.ravel(), yy.ravel()]

    # TODO: run forward pass on grid
    Z = np.zeros((grid.shape[0], 1))

    Z = Z.reshape(xx.shape)

    plt.contourf(xx, yy, Z, alpha=0.5)
    plt.scatter(X[:,0], X[:,1], c=y.flatten())
    plt.show()

"""## Run Training"""

# Train your model
# model = train(X, y)

# plot_decision_boundary(X, y, model)

"""
---

## ⭐ Extra Credit ( For Concept And Code, 20% add on )

### Circle Classification Problem

Instead of a checkerboard, classify points based on whether they lie inside a circle:

- Input: (x, y)
- Output: 1 if inside circle, else 0

Decision boundary:
x² + y² < r²

### Questions:
1. Why is this non-linear?
2. Would a single-layer perceptron work?
3. How would the decision boundary differ from the checkerboard?

---

"""